// import React from 'react'
// import ReactDOM from 'react-dom/client'
// import { BrowserRouter } from 'react-router-dom' // 1. BrowserRouter 임포트
// import App from './App'
// // import './index.css' //0204_충돌로 인한 주석처리[이예림]
//
// ReactDOM.createRoot(document.querySelector('.wrap')).render(
//   <React.StrictMode>
//     {/* 2. App 컴포넌트를 BrowserRouter로 감싸줍니다. */}
//     <BrowserRouter>
//       <App />
//     </BrowserRouter>
//   </React.StrictMode>
// )

// main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'

// 1. 브라우저가 기본으로 생성한 body를 찾습니다.
const body = document.body;

// 2. 리액트가 멋대로 만든 #root가 있다면 즉시 삭제 (연결 고리 차단)
const autoGeneratedRoot = document.getElementById('root');
if (autoGeneratedRoot) autoGeneratedRoot.remove();

// 3. 진짜 사용할 .wrap 상자를 자바스크립트로 직접 만듭니다.
const wrap = document.createElement('div');
wrap.className = 'wrap';

// 4. 이 .wrap을 body에 딱 붙여서 물리적 뼈대를 만듭니다.
body.appendChild(wrap);

// 5. 이제 리액트 엔진을 이 .wrap에 박아넣습니다.
ReactDOM.createRoot(wrap).render(
    <React.StrictMode>
        <BrowserRouter>
            <App />
        </BrowserRouter>
    </React.StrictMode>
);